"""empty message

Revision ID: 71ff6c0da15e
Revises: 
Create Date: 2018-07-07 19:54:30.169268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ff6c0da15e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=128), nullable=True),
    sa.Column('location_description', sa.String(length=128), nullable=True),
    sa.Column('location_x', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
